pub use general::*;
pub use memory::*;
pub use stack::*;

use crate::sasm::{Action, Processor};

mod general;
mod memory;
mod stack;

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum Instruction {
    // General
    Unreachable = 0,
    Nop,
    Debug,

    // Memory
    MemorySize = 12,
    MemoryGrow,
    MemoryFill8,
    MemoryFill16,
    MemoryFill32,
    MemoryFill64,
    MemoryCopy,
    MemoryLoad8,
    MemoryLoad16,
    MemoryLoad32,
    MemoryLoad64,
    MemoryStore8,
    MemoryStore16,
    MemoryStore32,
    MemoryStore64,
    ProgramDataLoad8,
    ProgramDataLoad16,
    ProgramDataLoad32,
    ProgramDataLoad64,

    // Stack
    Drop8 = 40,
    Drop16,
    Drop32,
    Drop64,
    Const8,
    Const16,
    Const32,
    Const64,
}

impl Instruction {
    // GETTERS ----------------------------------------------------------------

    pub fn index(&self) -> usize {
        *self as usize
    }

    pub fn method(&self) -> fn(&mut Processor) -> Action {
        let index = *self as usize;
        INSTRUCTION_LIST[index]
    }
}

pub static INSTRUCTION_LIST: [fn(&mut Processor) -> Action; 256] = [
    // General
    unreachable, // 0
    nop,
    debug,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 10
    unreachable,
    memory_size,
    memory_grow,
    memory_fill_8,
    memory_fill_16,
    memory_fill_32,
    memory_fill_64,
    memory_copy,
    memory_load_8,
    memory_load_16, // 20
    memory_load_32,
    memory_load_64,
    memory_store_8,
    memory_store_16,
    memory_store_32,
    memory_store_64,
    program_data_load_8,
    program_data_load_16,
    program_data_load_32,
    program_data_load_64, // 30
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    drop_8, // 40
    drop_16,
    drop_32,
    drop_64,
    const_8,
    const_16,
    const_32,
    const_64,
    unreachable,
    unreachable,
    unreachable, // 50
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 60
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 70
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 80
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 90
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 100
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 110
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 120
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 130
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 140
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 150
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 160
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 170
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 180
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 190
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 200
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 210
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 220
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 230
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 240
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 250
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
];
