pub use arithmetic::*;
pub use general::*;
pub use memory::*;
pub use stack::*;

use crate::sasm::{Action, Processor};

mod arithmetic;
mod general;
mod memory;
mod stack;

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum Instruction {
    // General
    Unreachable = 0,
    Nop,
    Debug,
    Branch,
    BranchIf8,
    BranchIf16,
    BranchIf32,
    BranchIf64,

    // Memory
    MemorySize = 12,
    MemoryGrow,
    MemoryFill8,
    MemoryFill16,
    MemoryFill32,
    MemoryFill64,
    MemoryCopy,
    MemoryLoad8,
    MemoryLoad16,
    MemoryLoad32,
    MemoryLoad64,
    MemoryStore8,
    MemoryStore16,
    MemoryStore32,
    MemoryStore64,
    ProgramDataLoad8,
    ProgramDataLoad16,
    ProgramDataLoad32,
    ProgramDataLoad64,

    // Stack
    Drop8 = 40,
    Drop16,
    Drop32,
    Drop64,
    Const8,
    Const16,
    Const32,
    Const64,

    // Arithmetic
    Extend8To16 = 70,
    Extend8To32,
    Extend16To32,
    Extend8To64,
    Extend16To64,
    Extend32To64,
    ExtendSign8To16,
    ExtendSign8To32,
    ExtendSign16To32,
    ExtendSign8To64,
    ExtendSign16To64,
    ExtendSign32To64,
    Trunc16To8,
    Trunc32To8,
    Trunc64To8,
    Trunc64To16,
    Trunc64To32,
}

impl Instruction {
    // GETTERS ----------------------------------------------------------------

    pub fn index(&self) -> usize {
        *self as usize
    }

    pub fn method(&self) -> fn(&mut Processor) -> Result<(), Action> {
        let index = *self as usize;
        INSTRUCTION_LIST[index]
    }
}

pub type InstructionFunction = fn(&mut Processor) -> Result<(), Action>;

pub static INSTRUCTION_LIST: [InstructionFunction; 256] = [
    // General
    unreachable, // 0
    nop,
    debug,
    branch,
    branch_if_8,
    branch_if_16,
    branch_if_32,
    branch_if_64,
    unreachable,
    unreachable,
    unreachable, // 10
    unreachable,
    memory_size,
    memory_grow,
    memory_fill_8,
    memory_fill_16,
    memory_fill_32,
    memory_fill_64,
    memory_copy,
    memory_load_8,
    memory_load_16, // 20
    memory_load_32,
    memory_load_64,
    memory_store_8,
    memory_store_16,
    memory_store_32,
    memory_store_64,
    program_data_load_8,
    program_data_load_16,
    program_data_load_32,
    program_data_load_64, // 30
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    drop_8, // 40
    drop_16,
    drop_32,
    drop_64,
    const_8,
    const_16,
    const_32,
    const_64,
    unreachable,
    unreachable,
    unreachable, // 50
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 60
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    extend_8_to_16, // 70
    extend_8_to_32,
    extend_16_to_32,
    extend_8_to_64,
    extend_16_to_64,
    extend_32_to_64,
    extend_sign_8_to_16,
    extend_sign_8_to_32,
    extend_sign_16_to_32,
    extend_sign_8_to_64,
    extend_sign_16_to_64, // 80
    extend_sign_32_to_64,
    trunc_16_to_8,
    trunc_32_to_8,
    trunc_64_to_8,
    trunc_64_to_16,
    trunc_64_to_32,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 90
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 100
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 110
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 120
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 130
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 140
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 150
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 160
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 170
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 180
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 190
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 200
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 210
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 220
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 230
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 240
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 250
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
];
