pub use general::*;
pub use memory::*;
pub use stack::*;

use crate::sasm::{Action, Processor};

mod general;
mod memory;
mod stack;

#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum Instruction {
    Unreachable = 0,
    Nop,
    Debug,
}

impl Instruction {
    // GETTERS ----------------------------------------------------------------

    pub fn index(&self) -> usize {
        *self as usize
    }

    pub fn method(&self) -> fn(&mut Processor) -> Action {
        let index = *self as usize;
        INSTRUCTION_LIST[index]
    }
}

pub static INSTRUCTION_LIST: [fn(&mut Processor) -> Action; 256] = [
    // General
    unreachable, // 0
    nop,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 10
    unreachable,
    memory_size,
    memory_grow,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 20
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    drop_8,
    drop_16,
    drop_32,
    drop_64,
    unreachable, // 30
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 40
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 50
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 60
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 70
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 80
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 90
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 100
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 110
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 120
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 130
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 140
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 150
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 160
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 170
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 180
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 190
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 200
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 210
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 220
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 230
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 240
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable, // 250
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
    unreachable,
];
